### ISSUE TITLE
problem with elasticsearch 6.x

### ISSUE THREAD

**Issue by veronesip** [NLPchina/elasticsearch-site#5]
Hi,
i have a problem after the upgrade of elasticsearch from 5.5 to 6.1, here some lines from jcoder.log:

> init begin !
> env in system.propertie: jcoder_home : /opt/elasticsearch-site-master/./jcoder_home
> env in system.propertie: jcoder_host : *
> env in system.propertie: jcoder_port : 8080
> env in system.propertie: jcoder_rpcport : 8081
> env in system.propertie: jcoder_log : log/jcoder.log
> env in system.propertie: jcoder_resource : /opt/elasticsearch-site-master/./jcoder_home/resource
> env in system.propertie: jcoder_lib : /opt/elasticsearch-site-master/./jcoder_home/lib
> env in system.propertie: jcoder_plugins : /opt/elasticsearch-site-master/./jcoder_home/plugins
> env in system.propertie: jcoder_upload : /opt/elasticsearch-site-master/./jcoder_home/upload
> database path is ./jcoder_home/h2db/jcoder begin start...
> database path is /opt/elasticsearch-site-master/./jcoder_home/h2db/jcoder
> the database is active good luck for use it !
> db has startd ， good luck !...
> begin Jar init!
> to flush classloader
> find JAR ./jcoder_home/lib/elasticsearch-site-0.2.jar
> find JAR ./jcoder_home/lib/target/dependency/HdrHistogram-2.1.6.jar
> find JAR ./jcoder_home/lib/target/dependency/activation-1.1.jar
> find JAR ./jcoder_home/lib/target/dependency/bcpkix-jdk15on-1.55.jar
> find JAR ./jcoder_home/lib/target/dependency/bcprov-jdk15on-1.55.jar
> find JAR ./jcoder_home/lib/target/dependency/commons-codec-1.10.jar
> find JAR ./jcoder_home/lib/target/dependency/commons-lang3-3.5.jar
> find JAR ./jcoder_home/lib/target/dependency/commons-logging-1.1.3.jar
> find JAR ./jcoder_home/lib/target/dependency/compiler-0.9.3.jar
> find JAR ./jcoder_home/lib/target/dependency/druid-1.0.15.jar
> find JAR ./jcoder_home/lib/target/dependency/elasticsearch-5.2.0.jar
> find JAR ./jcoder_home/lib/target/dependency/elasticsearch-sql-5.1.2.0.jar
> find JAR ./jcoder_home/lib/target/dependency/guava-15.0.jar
> find JAR ./jcoder_home/lib/target/dependency/hamcrest-core-1.3.jar
> find JAR ./jcoder_home/lib/target/dependency/hppc-0.7.1.jar
> find JAR ./jcoder_home/lib/target/dependency/httpasyncclient-4.1.2.jar
> find JAR ./jcoder_home/lib/target/dependency/httpclient-4.5.2.jar
> find JAR ./jcoder_home/lib/target/dependency/httpcore-4.4.5.jar
> find JAR ./jcoder_home/lib/target/dependency/httpcore-nio-4.4.5.jar
> find JAR ./jcoder_home/lib/target/dependency/jackson-core-2.8.6.jar
> find JAR ./jcoder_home/lib/target/dependency/jackson-dataformat-cbor-2.8.6.jar
> find JAR ./jcoder_home/lib/target/dependency/jackson-dataformat-smile-2.8.6.jar
> find JAR ./jcoder_home/lib/target/dependency/jackson-dataformat-yaml-2.8.6.jar
> find JAR ./jcoder_home/lib/target/dependency/javax.mail-1.5.3.jar
> find JAR ./jcoder_home/lib/target/dependency/jconsole-1.8.0.jar
> find JAR ./jcoder_home/lib/target/dependency/jna-4.2.2.jar
> find JAR ./jcoder_home/lib/target/dependency/joda-time-2.9.5.jar
> find JAR ./jcoder_home/lib/target/dependency/jopt-simple-5.0.2.jar
> find JAR ./jcoder_home/lib/target/dependency/jts-1.13.jar
> find JAR ./jcoder_home/lib/target/dependency/junit-4.12.jar
> find JAR ./jcoder_home/lib/target/dependency/lang-mustache-client-5.2.0.jar
> find JAR ./jcoder_home/lib/target/dependency/lucene-analyzers-common-6.4.0.jar
> find JAR ./jcoder_home/lib/target/dependency/lucene-backward-codecs-6.4.0.jar
> find JAR ./jcoder_home/lib/target/dependency/lucene-core-6.4.0.jar
> find JAR ./jcoder_home/lib/target/dependency/lucene-grouping-6.4.0.jar
> find JAR ./jcoder_home/lib/target/dependency/lucene-highlighter-6.4.0.jar
> find JAR ./jcoder_home/lib/target/dependency/lucene-join-6.4.0.jar
> find JAR ./jcoder_home/lib/target/dependency/lucene-memory-6.4.0.jar
> find JAR ./jcoder_home/lib/target/dependency/lucene-misc-6.4.0.jar
> find JAR ./jcoder_home/lib/target/dependency/lucene-queries-6.4.0.jar
> find JAR ./jcoder_home/lib/target/dependency/lucene-queryparser-6.4.0.jar
> find JAR ./jcoder_home/lib/target/dependency/lucene-sandbox-6.4.0.jar
> find JAR ./jcoder_home/lib/target/dependency/lucene-spatial-6.4.0.jar
> find JAR ./jcoder_home/lib/target/dependency/lucene-spatial-extras-6.4.0.jar
> find JAR ./jcoder_home/lib/target/dependency/lucene-spatial3d-6.4.0.jar
> find JAR ./jcoder_home/lib/target/dependency/lucene-suggest-6.4.0.jar
> find JAR ./jcoder_home/lib/target/dependency/netty-3.10.6.Final.jar
> find JAR ./jcoder_home/lib/target/dependency/netty-buffer-4.1.7.Final.jar
> find JAR ./jcoder_home/lib/target/dependency/netty-codec-4.1.7.Final.jar
> find JAR ./jcoder_home/lib/target/dependency/netty-codec-http-4.1.7.Final.jar
> find JAR ./jcoder_home/lib/target/dependency/netty-common-4.1.7.Final.jar
> find JAR ./jcoder_home/lib/target/dependency/netty-handler-4.1.7.Final.jar
> find JAR ./jcoder_home/lib/target/dependency/netty-resolver-4.1.7.Final.jar
> find JAR ./jcoder_home/lib/target/dependency/netty-transport-4.1.7.Final.jar
> find JAR ./jcoder_home/lib/target/dependency/owasp-java-html-sanitizer-r239.jar
> find JAR ./jcoder_home/lib/target/dependency/percolator-client-5.2.0.jar
> find JAR ./jcoder_home/lib/target/dependency/reindex-client-5.2.0.jar
> find JAR ./jcoder_home/lib/target/dependency/rest-5.2.0.jar
> find JAR ./jcoder_home/lib/target/dependency/securesm-1.1.jar
> find JAR ./jcoder_home/lib/target/dependency/snakeyaml-1.15.jar
> find JAR ./jcoder_home/lib/target/dependency/sniffer-5.2.0.jar
> find JAR ./jcoder_home/lib/target/dependency/spatial4j-0.6.jar
> find JAR ./jcoder_home/lib/target/dependency/t-digest-3.0.jar
> find JAR ./jcoder_home/lib/target/dependency/tools-1.8.0.jar
> find JAR ./jcoder_home/lib/target/dependency/transport-5.2.0.jar
> find JAR ./jcoder_home/lib/target/dependency/transport-netty3-client-5.2.0.jar
> find JAR ./jcoder_home/lib/target/dependency/transport-netty4-client-5.2.0.jar
> find JAR ./jcoder_home/lib/target/dependency/unboundid-ldapsdk-3.2.0.jar
> find JAR ./jcoder_home/lib/target/dependency/x-pack-api-5.2.0.jar
> find JAR ./jcoder_home/lib/target/dependency/x-pack-transport-5.2.0.jar
> Using default implementation for ThreadExecutor
> Job execution threads will use class loader of thread: main
> Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
> Quartz Scheduler v.2.2.1 created.
> RAMJobStore initialized.
> Scheduler meta-data: Quartz Scheduler (v2.2.1) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
>   Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
>   NOT STARTED.
>   Currently in standby mode.
>   Number of jobs executed: 0
>   Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
>   Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.
> 
> Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
> Quartz scheduler version: 2.2.1
> Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
> to flush ioc
> begin init all task by db !
> Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED shutting down.
> Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED paused.
> Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED shutdown complete.
> Using default implementation for ThreadExecutor
> Job execution threads will use class loader of thread: main
> Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
> Quartz Scheduler v.2.2.1 created.
> RAMJobStore initialized.
> Scheduler meta-data: Quartz Scheduler (v2.2.1) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
>   Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
>   NOT STARTED.
>   Currently in standby mode.
>   Number of jobs executed: 0
>   Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
>   Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.
> 
> Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
> Quartz scheduler version: 2.2.1
> Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
> begin init all task ok !
> begin run task quene!
> begin print console job!
> begin start rpc server! on port 8081
> to start rpc server
> websocket service starting
> start rpc server ok
> add class org.nlpcn.jcoder.controller.ConsoleAction in websocket container
> start all ok , goodluck
> to compile org.nlpcn.elasticsearch.site.sql.SqlApi
> org.nlpcn.elasticsearch.site.sql.SqlApi none @DefaultExecute annotation method : so set the firest method to DefaultExecute function:explain
> to instance with ioc className: org.nlpcn.elasticsearch.site.sql.SqlApi
> no modules loaded
> loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
> loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
> loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
> loaded plugin [org.elasticsearch.transport.Netty3Plugin]
> loaded plugin [org.elasticsearch.transport.Netty4Plugin]
> adding transport node : 127.0.0.1:9300
> failed to get local cluster state for {#transport#-1}{ljTqrzsLSnmg9JVdqCsTHw}{127.0.0.1}{127.0.0.1:9300}, disconnecting...
> org.elasticsearch.transport.NodeDisconnectedException: [][127.0.0.1:9300][cluster:monitor/state] disconnected

# cat jcoder_home/resource/ioc.js
var ioc = {
    esClient: {
        type: "org.nlpcn.elasticsearch.site.ESClient",
        args: ["127.0.0.1:9300"],
  //      args: [true, "elastic:changeme","127.0.0.1:9300"],
        events: {
            depose: 'destroy'
        }
    }
};

# netstat -tunpl|grep 9300
tcp        0      0 172.29.52.36:9300       0.0.0.0:*               LISTEN      25244/java
tcp        0      0 127.0.0.1:9300          0.0.0.0:*               LISTEN      25244/java

And the error on the elasticsearch log:

> [2018-01-16T10:21:08,438][WARN ][o.e.t.n.Netty4Transport  ] [eladevsolelbr01vm.cup2000.priv] exception caught on transport layer [org.elasticsearch.transport.netty4.NettyTcpChannel@1bf37d0d], closing connection
> java.lang.IllegalStateException: Received message from unsupported version: [5.2.0] minimal compatible version is: [5.6.0]
>         at org.elasticsearch.transport.TcpTransport.ensureVersionCompatibility(TcpTransport.java:1428) ~[elasticsearch-6.1.1.jar:6.1.1]
>         at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1375) ~[elasticsearch-6.1.1.jar:6.1.1]
>         at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:64) ~[transport-netty4-6.1.1.jar:6.1.1]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
>         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-codec-4.1.13.Final.jar:4.1.13.Final]
>         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) [netty-codec-4.1.13.Final.jar:4.1.13.Final]
>         at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) [netty-codec-4.1.13.Final.jar:4.1.13.Final]
>         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [netty-codec-4.1.13.Final.jar:4.1.13.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
>         at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
>         at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) [netty-handler-4.1.13.Final.jar:4.1.13.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
>         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
>         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
>         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
>         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
>         at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
>         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
>         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
>         at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.13.Final.jar:4.1.13.Final]
>         at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by veronesip** [comment]
Thank you so much, it works!
